site_name: MoViagem
docs_dir: gitpages/docs
repo_url: https://github.com/mdsreq-fga-unb/2023.1-MoViagem
repo_name: MoViagem

nav:
  - Inicio: index.md
  - Visão do produto e projeto:
      - Visão do produto e projeto: documentos/visao-do-produto-e-projeto.md
      - Abordagem Gupta: documentos/abordagem-gupta.md
  - Entregas Unidade 1:
      - Ciclos de Vida - Scrum: apresentacoes/ciclos-de-vida.md
      - Processos de ER: apresentacoes/processos-de-ER.md
  - Entregas Unidade 2:
      - Backlog: documentos/backlog.md
      - Pontuação dos requisitos: documentos/pontuacao-requisitos.md
      - História da Engenharia de Requisitos: documentos/historia-engenharia-de-requisitos.md
      - MVPs:
          - MVP 1: documentos/mvp1.md
          - MVP 2: documentos/mvp2.md
  - Entregas Unidade 3:
      - PBB e BDD: documentos/pbb-e-bdd.md
      - BACKLOG SAFe: documentos/backlog-SAFe.md
  - Entregas Unidade 4:
      - USM: documentos/usm.md
      - Diagrama de Casos de Uso: documentos/diagrama-casos-de-uso.md
      - Especificações de Casos de Uso:
          - Criar eventos no cronograma: documentos/especificacoes-caso-de-uso/joao-caso-de-uso.md
          - Visualizar lista de viagens: documentos/especificacoes-caso-de-uso/gabriel-caso-de-uso.md
          - Definir editores da viagem: documentos/especificacoes-caso-de-uso/eduardo-caso-de-uso.md
          - Editar informações básicas da viagem: documentos/especificacoes-caso-de-uso/pedro-caso-de-uso.md
          - Adicionar participantes na viagem: documentos/especificacoes-caso-de-uso/siqueira-caso-de-uso.md
  - Sprints:
      - Sprints: documentos/relato-iteracoes.md 

extra_css:
  - css/custom.css

theme:
  name: "material"
  language: "pt"
  palette:
    primary: "indigo"
    accent: "indigo"
  font:
    text: "Roboto"
    code: "Roboto Mono"
  feature:
    - navigation.tabs
    - navigation.expand
    - navigation.sections
    - navigation.top
    - toc.numbered
  search: true
  search_index_only: ["content"]
