site_name: MoViagem
docs_dir: gitpages/docs
repo_url: https://github.com/mdsreq-fga-unb/2023.1-MoViagem
repo_name: MoViagem

nav: 
 - Inicio: index.md
 - Visão do produto e projeto: documentos/visao-do-produto-e-projeto.md
 - Apresentações:
      - Ciclos de Vida - Scrum: apresentacoes/ciclos-de-vida.md
      - Processos de ER: apresentacoes/processos-de-ER.md

extra_css: 
  - css/custom.css

theme:
  name: 'material'
  language: 'pt'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  feature:
    - navigation.tabs
    - navigation.expand
    - navigation.sections
    - navigation.top
    - toc.numbered
  search: true
  search_index_only: ['content']